### ISSUE TITLE
Support 'share-safe' requirement

### ISSUE THREAD

**Issue by migmedia** [kilork/hg-parser#4]
```
thread 'main' panicked at /home/mig/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hg-parser-0.8.0/src/lib.rs:150:41:
could not parse requirement: UnknownRequirement("share-safe")
```

As far as I understand the mercurial specs, this requirement can be ignored in read-only usecases.

**Comment by kilork** [comment]
I usually just edit this file before import. But for sure we need to give a flag to threat requirement parse errors as warnings.
